version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8088:80"
  tomcat:
    image: tomcat:9.0.13-jre11-slim
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
